### ISSUE TITLE
Ближайшие задачи по фронтенду

### ISSUE THREAD

**Issue by kadukm** [mmokeev/memkeeper#32]
По ходу дела задачи будут добавляться. Мне пока вот что в голову пришло:

### Точно надо сделать:
- Поправить отображение длинных текстов заметок
- Отображать кнопку с удалением заметки в крайней правой стороне
- Поправить язык для ответов Yes/No при удалении вкладки
- Отображать дату создания заметки без этого миллисекунд (и, возможно, секунд - надо решить)
- Сделать так, чтобы окно создания новой заметки было более аккурантым, а не растягивалось уродливо на весь экран и не делилось пополам между метками и инпутами
- Аналогично сделать аккуратное наполнение вкладки "Добавить", чтобы пространство не делилось пополам
- Покрасить кнопки удаления в яркие цвета, чтобы было понятно, что это удаление и здесь опасно
- Добавить небольшой :hover для заметок
- Удалить :hover для страниц добавления заметок и вкладок
- Написать стили для .created-at и .text

### Сделать, если будет время:
- \* Изменить цвет у кнопки Yes при удалении вкладки
- \* Убрать отображение ошибки, если пользователь вообще не прикасался к полю title при добавлении новой заметки
- \* Поправить всплывающий на мгновение ненужный контент при клике на первую вкладку

Если будут какие-то пожелания/идеи, то тоже пиши сюда в комменты.

**Comment by kadukm** [comment]
- Менее агрессивно удалять заметки (может тоже диалоговое окно показывать или дать возможность восстановить удалённую заметку)

**Comment by mmokeev** [comment]
Я бы еще в принципе уменьшил размер даты, а то это особо не важная вспомогательная информация, но размером чуть ли не больше всего остального

**Comment by mmokeev** [comment]
> Менее агрессивно удалять заметки (может тоже диалоговое окно показывать или дать возможность восстановить удалённую заметку)

Можно на бэке не удалять заметки/вкладки, а проставлять deleted_at. Фронту это не поможет, но если че можно будет восстанавливать вручную в базе (так и работает продакшен)

**Comment by kadukm** [comment]
> Можно на бэке не удалять заметки/вкладки, а проставлять deleted_at. Фронту это не поможет, но если че можно будет восстанавливать вручную в базе (так и работает продакшен)

Да, крутая идея, давай так и сделаем (можешь добавить себе в задачи по бэку). Но на фронте я все равно подумаю, как сделать менее агрессивное удаление
